version: '2'
services:
    spacemanapp-app:
        image: spacemanapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://spacemanapp-mysql:3306/spacemanapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=spacemanapp-elasticsearch:9300
        ports:
            - 8080:8080
    spacemanapp-mysql:
        extends:
            file: mysql.yml
            service: spacemanapp-mysql
    spacemanapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: spacemanapp-elasticsearch
